---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: dev
spec:
  encryptedData:
    DB_PASSWORD: AgCJ/NHLs0ADZM3SjHnKmlg4g/cp2Lmd7R0rNdqJzEs4W2hHcq5gmvobwHpQCvRu0rZeoCKWJYgjCOV98FW/uauoZmKbSH6xD+N7X0ZaoKlBprosNBmYFXAKGBto7BmO2S+mAxw8sZ/zBgDC3esVrMDLR2DQXyVd/K0iUZtuY1tN/ZAiCVnrCHh8knGagfQh0EX0ZXQoTNY+J2SqSLTPkJrICZMIJ6yhtABvzCsucdgmdEKXVGnBZmfxd9wiN1VWo1Xc02Q149cCwTq27QATaCIaLSxO4mY0AQAWEH1fgJdajjmsuwlUaSbwgMaKapybGTz+8rW7d2RK03/QrUVzEFQU1SRPEVV0TI4elDJ5ae6BUSLdANyRjXP1tKNT0Z4QMfDxpngolVXJoAYgJi0XPk3zBb2BSh+gWPAfuuS75pA7NhAuqlxFxFPPctVSMBWOpZBXzxo3bbJjuRCDA/EQ2Lermy0gvuTDsWUIarAgWAGJcz1K804SsIfktjxHdsAAMaM0wO9GKYhRbEHtc0ci0wNcmIfVlj1o4sx5j5I4STwsi2cpRsVL4gfMUjO4WISjttYG9kmCPONPVx5I98jw3ZyoNNh66eDqm4LySRfGh1c6bhB/i3Mjzr/IXmKLoi9+/JZVoe2mQawoIsbm/FAsieCrQLoWqxz6XgNfeHhNwZ6HcrrehXt4+qN2HXspaHNIapMzYDEN2TiZ2CXXLlUrzixEPwJGGaCF
  template:
    metadata:
      name: db-credentials
      namespace: dev
